### ISSUE TITLE
shorturls/add should handle invalid characters

### ISSUE THREAD

**Issue by fydai** [ocf/ircbot#151]
When the command `!shorturl add ^fieldunits <redacted>` was run, the following error was reported.

A problem was encountered and reported via ocflib:

ircbot exception in shorturls/add: shorturl '^fieldunits' contains illegal characters

Traceback (most recent call last):
  File "/opt/ircbot/ircbot/ircbot.py", line 250, in on_pubmsg
    listener.fn(self, msg)
  File "ircbot/plugin/shorturls.py", line 45, in add
    add_shorturl(ctx, slug, target)
  File "/opt/ircbot/venv/lib/python3.7/site-packages/ocflib/misc/shorturls.py", line 38, in add_shorturl
    _validate_slug(slug)
  File "/opt/ircbot/venv/lib/python3.7/site-packages/ocflib/misc/shorturls.py", line 22, in _validate_slug
    raise ValueError("shorturl '{}' contains illegal characters".format(slug))
ValueError: shorturl '^fieldunits' contains illegal characters

**Comment by zpfeiffer** [comment]
Fixed by #156
